name: a1_check_cashers
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.13+13


environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  google_fonts: ^8.0.2
  connectivity_plus: ^7.0.0
  provider: ^6.1.5+1
  http: ^1.6.0
  image_picker: ^1.2.1
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  dotted_border: ^3.1.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  url_launcher: ^6.3.2
  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_dotenv: ^6.0.1
  package_info_plus: ^9.0.1
  internet_connection_checker_plus: ^3.1.1
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
  assets:
    - assets/images/
    - .env
flutter_launcher_icons:
  ios: true
  android: true
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png"
  remove_alpha_ios: true
